/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorBaseDeDatos;
import javax.swing.JOptionPane;
import modelo.Empleado;

/**
 *
 * @author Ventura
 */
public class AltaPanel extends javax.swing.JPanel {

    /**
     * Creates new form AltaPanel
     */
    public AltaPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nombreText = new javax.swing.JTextField();
        apPaternoText = new javax.swing.JTextField();
        apMaternoText = new javax.swing.JTextField();
        telefonoText = new javax.swing.JTextField();
        correoText = new javax.swing.JTextField();
        masculinoRadio = new javax.swing.JRadioButton();
        femeninoRadio = new javax.swing.JRadioButton();
        sueldoText = new javax.swing.JTextField();
        edadComboBox = new javax.swing.JComboBox<>();
        enviarButton = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setPreferredSize(new java.awt.Dimension(300, 300));

        jLabel1.setText("Nombre");

        jLabel2.setText("Apellido Paterno");

        jLabel3.setText("Apellido Materno");

        jLabel4.setText("Teléfono");

        jLabel5.setText("Correo");

        jLabel6.setText("Sexo");

        jLabel7.setText("Sueldo");

        jLabel8.setText("Edad");

        nombreText.setPreferredSize(new java.awt.Dimension(100, 20));

        apPaternoText.setPreferredSize(new java.awt.Dimension(100, 20));

        apMaternoText.setPreferredSize(new java.awt.Dimension(100, 20));

        telefonoText.setPreferredSize(new java.awt.Dimension(100, 20));

        correoText.setPreferredSize(new java.awt.Dimension(100, 20));

        masculinoRadio.setText("M");

        femeninoRadio.setText("F");

        sueldoText.setPreferredSize(new java.awt.Dimension(100, 20));

        edadComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "18", "19", "20", "21", "22", "23", "24" }));

        enviarButton.setText("Enviar");
        enviarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enviarButton)
                    .addComponent(edadComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sueldoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(masculinoRadio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(femeninoRadio))
                    .addComponent(correoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefonoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apMaternoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apPaternoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel1)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jLabel2))
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addComponent(nombreText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(apPaternoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jLabel3))
                                                    .addComponent(apMaternoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel4))
                                            .addComponent(telefonoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel5))
                                    .addComponent(correoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(masculinoRadio)
                                .addComponent(femeninoRadio)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7))
                    .addComponent(sueldoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(edadComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(enviarButton)
                .addContainerGap(34, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void enviarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarButtonActionPerformed
        String nombre = nombreText.getText();
        String apPaterno = apPaternoText.getText();
        String apMaterno = apMaternoText.getText();
        int sexo=-1;
        if(masculinoRadio.isSelected())
            sexo = 0;
        if(femeninoRadio.isSelected())
            sexo = 1;
        String correo = correoText.getText();
        String telefono = telefonoText.getText();
        String edadString = (String) edadComboBox.getSelectedItem();
        Integer edadInteger = new Integer(edadString);
        int edad = edadInteger.intValue();
        String sueldoString = sueldoText.getText();
        Float sueldoFloat = new Float(sueldoString);
        float sueldo = sueldoFloat.floatValue();
        //String nombre, String apPaterno, 
        //String apMaterno, String telefono, String correo, int sexo, int edad, float sueldo
        Empleado empleado = new Empleado(nombre,apPaterno,apMaterno,telefono,correo,sexo,edad,sueldo);
        ControladorBaseDeDatos  cont = new ControladorBaseDeDatos(); 
        
        if(cont.guardarEmpleadoControlador(empleado))
        {
            JOptionPane.showMessageDialog(this, "Guardado exitosamente.", "Guardado", JOptionPane.PLAIN_MESSAGE);
            limpiarCampos();
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Error, verifique sus datos.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_enviarButtonActionPerformed
    void limpiarCampos()
    {
        nombreText.setText("");
        apPaternoText.setText("");
        apMaternoText.setText("");
        buttonGroup1.clearSelection();
        correoText.setText("");
        telefonoText.setText("");
        edadComboBox.setSelectedIndex(0);
        sueldoText.setText("");
               
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apMaternoText;
    private javax.swing.JTextField apPaternoText;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField correoText;
    private javax.swing.JComboBox<String> edadComboBox;
    private javax.swing.JButton enviarButton;
    private javax.swing.JRadioButton femeninoRadio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton masculinoRadio;
    private javax.swing.JTextField nombreText;
    private javax.swing.JTextField sueldoText;
    private javax.swing.JTextField telefonoText;
    // End of variables declaration//GEN-END:variables
}
